// Copyright (c) 2022, Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

//! Compatibility tests for the PQClean-backed signer, checking KATs, etc
use crate::falcon512::sign::{keygen, keygen_from_seed, sign, KEYGEN_SEED_LEN};
use crate::falcon512::verify::{
    derive_public_key, verify_strict, PUBKEY_LEN, SECKEY_LEN, SIG_PADDED_LEN,
};
use crate::falcon512::{Falcon512KeyPair, Falcon512PublicKey};
use crate::falcon512_verify_tests::{parse_kat_vectors, to_canonical_padded};
use crate::traits::{KeyPair, Signer, ToFromBytes, VerifyingKey};
use pqcrypto_falcon::falconpadded512 as f512;
use pqcrypto_traits::sign::{DetachedSignature as _, PublicKey as _};
use rand::{rngs::StdRng, SeedableRng as _};

/// Lineage cross-check: keys generated by the reference implementation (the
/// KAT suite) must produce signatures our verifier accepts. This is the
/// strongest evidence that the PQClean signer and our hand-ported verifier
/// implement the same scheme.
#[test]
fn kat_keys_sign_for_our_verifier() {
    let vectors = parse_kat_vectors();
    assert_eq!(vectors.len(), 100, "expected the full NIST KAT suite");

    for v in &vectors {
        let sk: &[u8; SECKEY_LEN] = v.sk.as_slice().try_into().expect("KAT sk is 1281 bytes");
        let pk: &[u8; PUBKEY_LEN] = v.pk.as_slice().try_into().expect("KAT pk is 897 bytes");
        // A fresh message per vector; the KAT message itself would do, but a
        // distinct one shows the keys are usable beyond their recorded case.
        let msg = format!("kat lineage check {}", v.count);
        let sig = sign(sk, pk, msg.as_bytes()).expect("KAT secret key must sign");
        assert!(
            verify_strict(pk, msg.as_bytes(), &sig),
            "vector {}: signature must pass strict verify",
            v.count
        );
    }
}

/// Mutual consistency on identical canonical inputs: the padded form of each
/// KAT signature must verify under both the in-crate port and PQClean's own verifier.
#[test]
fn kat_signatures_verify_under_both_verifiers() {
    let vectors = parse_kat_vectors();

    for v in &vectors {
        let padded = to_canonical_padded(&v.sig);
        assert!(
            verify_strict(&v.pk, &v.msg, &padded),
            "vector {}: in-crate verifier",
            v.count
        );

        let pk = f512::PublicKey::from_bytes(&v.pk).expect("KAT pk parses");
        let sig = f512::DetachedSignature::from_bytes(&padded).expect("padded sig parses");
        assert!(
            f512::verify_detached_signature(&sig, &v.msg, &pk).is_ok(),
            "vector {}: PQClean verifier",
            v.count
        );
    }
}

#[test]
fn sign_verify_roundtrip_and_tamper() {
    let (sk, pk) = keygen();
    let msg = b"falcon-sign roundtrip";
    let sig = sign(&sk, &pk, msg).unwrap();
    assert!(verify_strict(&pk, msg, &sig));

    // One flipped byte anywhere must fail: signature body, message, or key.
    let mut bad = sig;
    bad[SIG_PADDED_LEN / 2] ^= 0x01;
    assert!(!verify_strict(&pk, msg, &bad));

    assert!(!verify_strict(&pk, b"falcon-sign roundtrip!", &sig));

    let mut bad_pk = pk;
    bad_pk[PUBKEY_LEN / 2] ^= 0x01;
    assert!(!verify_strict(&bad_pk, msg, &sig));
}

/// The signer must emit exactly the strict wire format, every time.
#[test]
fn signatures_are_strict_canonical_form() {
    let (sk, pk) = keygen();
    for msg in [&b"x"[..], b"", &[0u8; 1000]] {
        let sig = sign(&sk, &pk, msg).unwrap();
        assert_eq!(sig.len(), SIG_PADDED_LEN);
        assert_eq!(sig[0], 0x39);
    }
}

/// Keystore round-trip: flag ‖ sk, reload through the trait types, sign and
/// verify. The reloaded public key must match PQClean's, which pins the
/// derivation against PQClean keygen too.
#[test]
fn keystore_blob_roundtrip() {
    let (sk, pk) = keygen();
    let mut blob = vec![0xffu8];
    blob.extend_from_slice(&sk);

    let kp = Falcon512KeyPair::from_bytes(&blob[1..]).expect("blob body parses");
    let msg = b"keystore roundtrip";
    let sig = kp.sign(msg);
    assert!(kp.public().verify(msg, &sig).is_ok());
    assert_eq!(kp.public().as_ref(), &pk);

    // The byte and trait layers agree on the same key material.
    let pk = Falcon512PublicKey::from_bytes(&pk).unwrap();
    assert!(pk.verify(msg, &sig).is_ok());
}

// === Seeded key generation ===

/// The NIST KAT harness RNG (`rng.c`, AES256_CTR_DRBG): just enough of it to
/// replay the 48 bytes `crypto_sign_keypair` drew via `randombytes` for each
/// response vector. No personalization string, no prediction resistance.
struct AesCtrDrbg {
    key: [u8; 32],
    v: [u8; 16],
}

impl AesCtrDrbg {
    fn new(entropy: &[u8; 48]) -> Self {
        let mut drbg = AesCtrDrbg {
            key: [0; 32],
            v: [0; 16],
        };
        drbg.update(Some(entropy));
        drbg
    }

    /// `AES256_CTR_DRBG_Update`: temp = AES256(key, V+1 ‖ V+2 ‖ V+3), XOR the
    /// provided data in, then split temp into the next (key, V).
    fn update(&mut self, provided: Option<&[u8; 48]>) {
        use aes::cipher::{BlockEncrypt, KeyInit};
        let cipher = aes::Aes256::new_from_slice(&self.key).unwrap();
        let mut temp = [0u8; 48];
        for chunk in temp.chunks_mut(16) {
            Self::increment(&mut self.v);
            let mut block = aes::Block::clone_from_slice(&self.v);
            cipher.encrypt_block(&mut block);
            chunk.copy_from_slice(&block);
        }
        if let Some(data) = provided {
            for (t, d) in temp.iter_mut().zip(data) {
                *t ^= d;
            }
        }
        self.key.copy_from_slice(&temp[..32]);
        self.v.copy_from_slice(&temp[32..]);
    }

    /// Big-endian increment of the 128-bit counter V.
    fn increment(v: &mut [u8; 16]) {
        for byte in v.iter_mut().rev() {
            *byte = byte.wrapping_add(1);
            if *byte != 0 {
                break;
            }
        }
    }

    /// `randombytes`: AES256(key, V+i) blocks, then a keystate update.
    fn random_bytes(&mut self, out: &mut [u8]) {
        use aes::cipher::{BlockEncrypt, KeyInit};
        let cipher = aes::Aes256::new_from_slice(&self.key).unwrap();
        for chunk in out.chunks_mut(16) {
            Self::increment(&mut self.v);
            let mut block = aes::Block::clone_from_slice(&self.v);
            cipher.encrypt_block(&mut block);
            chunk.copy_from_slice(&block[..chunk.len()]);
        }
        self.update(None);
    }
}

/// The strongest claim about the seeded path: replaying each KAT vector's
/// DRBG reproduces the reference implementation's key pair bit-for-bit, for
/// all 100 vectors. This pins the frozen seed -> key map to the Round-3
/// reference code (the KATs predate PQClean's port), and doubles as a drift
/// alarm for the extern bindings if `pqcrypto-falcon` is ever bumped.
#[test]
fn keygen_seed_reproduces_reference_kats() {
    let vectors = parse_kat_vectors();
    assert_eq!(vectors.len(), 100, "expected the full NIST KAT suite");

    for v in &vectors {
        // In the KAT harness, keypair generation is the first randombytes
        // consumer after randombytes_init(seed), drawing exactly 48 bytes —
        // the same size and construction as the public seeded path.
        let entropy: &[u8; 48] = v.seed.as_slice().try_into().expect("KAT seed is 48 bytes");
        let mut keygen_seed = [0u8; KEYGEN_SEED_LEN];
        AesCtrDrbg::new(entropy).random_bytes(&mut keygen_seed);

        let (sk, pk) = keygen_from_seed(&keygen_seed);
        assert_eq!(sk.as_slice(), v.sk, "vector {}: secret key", v.count);
        assert_eq!(pk.as_slice(), v.pk, "vector {}: public key", v.count);
    }
}

/// Same seed, same key pair; different seed, different key pair; and the h
/// keygen emits agrees with our own g/f re-derivation from the secret key.
#[test]
fn keygen_from_seed_is_deterministic() {
    let seed = [42u8; KEYGEN_SEED_LEN];
    let (sk1, pk1) = keygen_from_seed(&seed);
    let (sk2, pk2) = keygen_from_seed(&seed);
    assert_eq!(sk1, sk2);
    assert_eq!(pk1, pk2);

    let (sk3, pk3) = keygen_from_seed(&[43u8; KEYGEN_SEED_LEN]);
    assert_ne!(sk1, sk3);
    assert_ne!(pk1, pk3);

    assert_eq!(
        derive_public_key(&sk1).expect("keygen output is a valid secret key"),
        pk1
    );

    // Derived keys are usable end to end.
    let msg = b"seeded keygen roundtrip";
    let sig = sign(&sk1, &pk1, msg).unwrap();
    assert!(verify_strict(&pk1, msg, &sig));
}

/// The trait path draws its seed from the caller's RNG, so a seeded `StdRng`
/// reproduces the key pair — the property sigs-cli relies on for its
/// `--seed` flag, and the exact opposite of the pre-seeded behavior this
/// module used to document.
#[test]
fn generate_is_deterministic_from_rng_seed() {
    let kp1 = Falcon512KeyPair::generate(&mut StdRng::from_seed([7u8; 32]));
    let kp2 = Falcon512KeyPair::generate(&mut StdRng::from_seed([7u8; 32]));
    assert_eq!(kp1, kp2);

    let kp3 = Falcon512KeyPair::generate(&mut StdRng::from_seed([8u8; 32]));
    assert_ne!(kp1, kp3);

    // generate() is exactly generate_from_seed() over the RNG's first draw.
    let mut seed = [0u8; KEYGEN_SEED_LEN];
    rand::RngCore::fill_bytes(&mut StdRng::from_seed([7u8; 32]), &mut seed);
    assert_eq!(kp1, Falcon512KeyPair::generate_from_seed(&seed));
}

/// The wallet derivation layer: HKDF-SHA3-256 under the fixed falcon label.
/// Deterministic, sensitive to both inputs, identical to running the two
/// steps by hand, and pinned so the mnemonic → account map can never drift.
/// The same inputs through `@noble/hashes`' `hkdf(sha3_256, ...)` produce
/// the same 48 bytes (the HKDF layer is standard and exact); whether the
/// keygen tail matches in TS is per-seed — see the module docs on noble
/// keygen equivalence.
#[test]
fn generate_from_ikm_is_deterministic_and_pinned() {
    use crate::falcon512::FALCON512_KEYGEN_HKDF_INFO;
    use crate::hash::{HashFunction, Sha256};
    use crate::hmac::{hkdf_sha3_256, HkdfIkm};

    let ikm = HkdfIkm::from_bytes(&[7u8; 32]).unwrap();
    let kp = Falcon512KeyPair::generate_from_ikm(&ikm, b"salt-a");
    assert_eq!(kp, Falcon512KeyPair::generate_from_ikm(&ikm, b"salt-a"));
    assert_ne!(kp, Falcon512KeyPair::generate_from_ikm(&ikm, b"salt-b"));
    let other_ikm = HkdfIkm::from_bytes(&[8u8; 32]).unwrap();
    assert_ne!(
        kp,
        Falcon512KeyPair::generate_from_ikm(&other_ikm, b"salt-a")
    );

    // The convenience function is exactly the two-step pipeline.
    let seed = hkdf_sha3_256(&ikm, b"salt-a", FALCON512_KEYGEN_HKDF_INFO, KEYGEN_SEED_LEN).unwrap();
    assert_eq!(
        kp,
        Falcon512KeyPair::generate_from_seed(&seed.as_slice().try_into().unwrap())
    );

    // Pin the full ikm → key map. If this fails, wallet derivation broke:
    // do not update the constant — find the drift.
    assert_eq!(
        hex::encode(Sha256::digest(kp.public().as_ref()).digest),
        "83dfdba714c241124d9d3077638f57ecc9a0b36e7d5763d9c6b44cba12653df3"
    );
}

/// Regression pin for the frozen map. These digests also match
/// `@noble/post-quantum` 0.6.1's `falcon512padded.keygen` for these exact
/// seeds (checked 2026-07-15) — but that equality is per-seed, not
/// universal: differential testing later found rare seeds (~1 in 10^3)
/// where noble's implementation-specific NTRU-solve bounds yield a
/// different valid key. This module, KAT-anchored, is canonical; see the
/// sign module docs. If this test fails, account derivation broke: do not
/// update the constants — find the drift.
#[test]
fn keygen_from_seed_pinned_vectors() {
    use crate::hash::{HashFunction, Sha256};
    for (seed, want_sk, want_pk) in [
        (
            [0u8; KEYGEN_SEED_LEN],
            "e18d9980ecd7dc95d2ef4c65be1101e7657433dd3ecaffb8b78e68935669581d",
            "049a39503b551ae8695c1ff40a16f12e7a40df3a1b666dd25f2c95a182487440",
        ),
        (
            [1u8; KEYGEN_SEED_LEN],
            "c24cb48c546579fe40bfe592a97beb442fd8a748dfa9b83523639ffc2d949dce",
            "21d87d4443761e214c23ca99028081670b1656a789bfa955dcd0a4ecfc3754cc",
        ),
    ] {
        let (sk, pk) = keygen_from_seed(&seed);
        assert_eq!(hex::encode(Sha256::digest(sk).digest), want_sk);
        assert_eq!(hex::encode(Sha256::digest(pk).digest), want_pk);
    }
}
