// Copyright (c) 2022, Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

//! Compatibility tests for the PQClean-backed signer, checking KATs, etc
use crate::falcon512::sign::{keygen, sign};
use crate::falcon512::verify::{verify_strict, PUBKEY_LEN, SECKEY_LEN, SIG_PADDED_LEN};
use crate::falcon512::{Falcon512KeyPair, Falcon512PublicKey};
use crate::falcon512_verify_tests::{parse_kat_vectors, to_canonical_padded};
use crate::traits::{KeyPair, Signer, ToFromBytes, VerifyingKey};
use pqcrypto_falcon::falconpadded512 as f512;
use pqcrypto_traits::sign::{DetachedSignature as _, PublicKey as _};

/// Lineage cross-check: keys generated by the reference implementation (the
/// KAT suite) must produce signatures our verifier accepts. This is the
/// strongest evidence that the PQClean signer and our hand-ported verifier
/// implement the same scheme.
#[test]
fn kat_keys_sign_for_our_verifier() {
    let vectors = parse_kat_vectors();
    assert_eq!(vectors.len(), 100, "expected the full NIST KAT suite");

    for v in &vectors {
        let sk: &[u8; SECKEY_LEN] = v.sk.as_slice().try_into().expect("KAT sk is 1281 bytes");
        let pk: &[u8; PUBKEY_LEN] = v.pk.as_slice().try_into().expect("KAT pk is 897 bytes");
        // A fresh message per vector; the KAT message itself would do, but a
        // distinct one shows the keys are usable beyond their recorded case.
        let msg = format!("kat lineage check {}", v.count);
        let sig = sign(sk, pk, msg.as_bytes()).expect("KAT secret key must sign");
        assert!(
            verify_strict(pk, msg.as_bytes(), &sig),
            "vector {}: signature must pass strict verify",
            v.count
        );
    }
}

/// Mutual consistency on identical canonical inputs: the padded form of each
/// KAT signature must verify under both the in-crate port and PQClean's own verifier.
#[test]
fn kat_signatures_verify_under_both_verifiers() {
    let vectors = parse_kat_vectors();

    for v in &vectors {
        let padded = to_canonical_padded(&v.sig);
        assert!(
            verify_strict(&v.pk, &v.msg, &padded),
            "vector {}: in-crate verifier",
            v.count
        );

        let pk = f512::PublicKey::from_bytes(&v.pk).expect("KAT pk parses");
        let sig = f512::DetachedSignature::from_bytes(&padded).expect("padded sig parses");
        assert!(
            f512::verify_detached_signature(&sig, &v.msg, &pk).is_ok(),
            "vector {}: PQClean verifier",
            v.count
        );
    }
}

#[test]
fn sign_verify_roundtrip_and_tamper() {
    let (sk, pk) = keygen();
    let msg = b"falcon-sign roundtrip";
    let sig = sign(&sk, &pk, msg).unwrap();
    assert!(verify_strict(&pk, msg, &sig));

    // One flipped byte anywhere must fail: signature body, message, or key.
    let mut bad = sig;
    bad[SIG_PADDED_LEN / 2] ^= 0x01;
    assert!(!verify_strict(&pk, msg, &bad));

    assert!(!verify_strict(&pk, b"falcon-sign roundtrip!", &sig));

    let mut bad_pk = pk;
    bad_pk[PUBKEY_LEN / 2] ^= 0x01;
    assert!(!verify_strict(&bad_pk, msg, &sig));
}

/// The signer must emit exactly the strict wire format, every time.
#[test]
fn signatures_are_strict_canonical_form() {
    let (sk, pk) = keygen();
    for msg in [&b"x"[..], b"", &[0u8; 1000]] {
        let sig = sign(&sk, &pk, msg).unwrap();
        assert_eq!(sig.len(), SIG_PADDED_LEN);
        assert_eq!(sig[0], 0x39);
    }
}

/// Keystore round-trip: flag ‖ sk, reload through the trait types, sign and
/// verify. The reloaded public key must match PQClean's, which pins the
/// derivation against PQClean keygen too.
#[test]
fn keystore_blob_roundtrip() {
    let (sk, pk) = keygen();
    let mut blob = vec![0xffu8];
    blob.extend_from_slice(&sk);

    let kp = Falcon512KeyPair::from_bytes(&blob[1..]).expect("blob body parses");
    let msg = b"keystore roundtrip";
    let sig = kp.sign(msg);
    assert!(kp.public().verify(msg, &sig).is_ok());
    assert_eq!(kp.public().as_ref(), &pk);

    // The byte and trait layers agree on the same key material.
    let pk = Falcon512PublicKey::from_bytes(&pk).unwrap();
    assert!(pk.verify(msg, &sig).is_ok());
}
